### ISSUE TITLE
フォントをグローバルに設定

### ISSUE THREAD

**Issue by lemonadern** [youngeek-0410/SekigaeService#152]
# 概要

~~英語：Roboto
日本語：Noto sans JP
でOK?
https://fonts.google.com/~~
一旦はいい感じの設定で

# 改善の背景

# 要件

重くなるの嫌なので一旦Web Fontの導入を見送らせてほしい
代替
 :point_down: 
```css
body {
  font-family: "Helvetica Neue",
    Arial,
    "Hiragino Kaku Gothic ProN",
    "Hiragino Sans",
    Meiryo,
    sans-serif;
}
```

# 検討事項

- 

# 実装方針

- base.html（css）で定義
